name: Build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: composer-installer-action
        run: make install
      - name: PHP Lint
        run: make lint

